# Generated by Django 5.2.1 on 2026-07-15 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_organization'),
        ('users', '0002_alter_template_created_at_alter_template_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together={('organization', 'name')},
        ),
    ]
