# Generated by Django 5.2.1 on 2026-07-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_template_organization_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned')], default='Active', max_length=20),
        ),
    ]
