# Generated by Django 5.2.1 on 2026-07-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_employee_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='denied_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, default='Employee', max_length=100),
        ),
    ]
