# Generated by Django 5.2.1 on 2026-07-31

import django.db.models.deletion
from django.db import migrations, models


def migrate_roles_and_permissions(apps, schema_editor):
    from users.roles import sync_default_roles
    sync_default_roles()

    Employee = apps.get_model('users', 'Employee')
    Role = apps.get_model('users', 'Role')
    PermissionFlag = apps.get_model('users', 'PermissionFlag')

    for emp in Employee.objects.all():
        r_title = getattr(emp, 'role_name', None) or getattr(emp, 'designation', None) or 'Employee'
        if emp.is_superuser or getattr(emp, 'isSuperAdmin', False) or r_title in ['Super Admin', 'Admin']:
            matched_role = Role.objects.filter(slug='super-admin').first()
        elif r_title == 'Company Admin':
            matched_role = Role.objects.filter(slug='company-admin').first()
        elif r_title in ['Project Manager', 'PM']:
            matched_role = Role.objects.filter(slug='project-manager').first()
        elif r_title in ['HR Manager', 'HR Executive']:
            matched_role = Role.objects.filter(slug='hr-manager').first()
        elif r_title == 'Attendance Manager':
            matched_role = Role.objects.filter(slug='attendance-manager').first()
        elif r_title == 'Viewer':
            matched_role = Role.objects.filter(slug='viewer').first()
        else:
            matched_role = Role.objects.filter(slug='employee').first()

        if matched_role:
            emp.role = matched_role
            emp.role_name = matched_role.name
            emp.save(update_fields=['role', 'role_name'])

        extra_json = getattr(emp, 'extra_permissions_json', []) or []
        if extra_json and isinstance(extra_json, list):
            extra_flags = PermissionFlag.objects.filter(key__in=extra_json)
            emp.extra_permissions.set(extra_flags)

        denied_json = getattr(emp, 'denied_permissions_json', []) or []
        if denied_json and isinstance(denied_json, list):
            denied_flags = PermissionFlag.objects.filter(key__in=denied_json)
            emp.denied_permissions.set(denied_flags)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailhistory_emailqueue_emaillog_html_content_and_more'),
        ('users', '0005_employee_denied_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(db_index=True, max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(db_index=True, default='General', max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_permission_flag',
                'ordering': ['module', 'category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('label', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permissionflag')),
            ],
            options={
                'db_table': 'api_role',
                'ordering': ['name'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='role',
            new_name='role_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='users.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='denied_permissions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employee',
            name='extra_permissions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='denied_permissions',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='extra_permissions',
        ),
        migrations.AddField(
            model_name='employee',
            name='denied_permissions',
            field=models.ManyToManyField(blank=True, related_name='denied_permission_employees', to='users.permissionflag'),
        ),
        migrations.AddField(
            model_name='employee',
            name='extra_permissions',
            field=models.ManyToManyField(blank=True, related_name='extra_permission_employees', to='users.permissionflag'),
        ),
        migrations.RunPython(migrate_roles_and_permissions),
    ]
