# Generated by Django 5.2.1 on 2026-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_permissionflag_employee_denied_permissions_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Official employment start date.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_working_date',
            field=models.DateField(blank=True, help_text='Official employment termination/last working date.', null=True),
        ),
    ]
