# Generated by Django 5.2.1 on 2026-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_joining_date_employee_last_working_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Department or team', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, help_text='HR / Payroll Employee ID', max_length=50, null=True),
        ),
    ]
