# Generated by Django 5.2.15 on 2026-09-14 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orgsettings_billing_email'),
        ('users', '0010_backfill_organization_memberships'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employee_code', models.CharField(blank=True, db_index=True, help_text='HR / Payroll Employee ID', max_length=50, null=True)),
                ('designation', models.CharField(blank=True, help_text='HR Job Title (e.g. Developer, QA, Designer)', max_length=100, null=True)),
                ('department', models.CharField(blank=True, default='', help_text='Department or team', max_length=100)),
                ('employment_status', models.CharField(choices=[('Active', 'Active'), ('Deactivated', 'Deactivated'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned')], default='Active', max_length=20)),
                ('joining_date', models.DateField(blank=True, help_text='Official employment start date.', null=True)),
                ('last_working_date', models.DateField(blank=True, help_text='Official employment termination/last working date.', null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_employeeprofile',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['organization', 'employee_code'], name='empprof_org_code_idx'), models.Index(fields=['organization', 'employment_status'], name='empprof_org_status_idx')],
            },
        ),
    ]
