# Generated by Django 5.2.1 on 2026-07-22 14:03
# Modified: Multi-step migration that:
#   1. Creates ProjectStatusOption table
#   2. Seeds status options per organization
#   3. Adds status_option FK columns (nullable) alongside old CharField
#   4. Populates new FK columns from old string values
#   5. Removes old CharField columns
#   (SQLite FK constraint issue avoided by seeding before applying FK constraints)

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Maps old string status values (lowercase) to the new status codes
STATUS_NAME_MAP = {
    # Project statuses
    'planning': 'pending',
    'active': 'in_progress',
    'on hold': 'pending',
    # Story statuses
    'todo': 'pending',
    'in progress': 'in_progress',
    'done': 'completed',
    # Task statuses
    'pending': 'pending',
    'completed': 'completed',
}

DEFAULT_STATUSES = [
    {'name': 'Pending', 'code': 'pending', 'category': 'pending', 'scope': 'all', 'order': 0, 'is_default': True, 'is_system': True, 'is_active': True},
    {'name': 'In Progress', 'code': 'in_progress', 'category': 'active', 'scope': 'all', 'order': 1, 'is_default': False, 'is_system': False, 'is_active': True},
    {'name': 'Completed', 'code': 'completed', 'category': 'completed', 'scope': 'all', 'order': 2, 'is_default': False, 'is_system': True, 'is_active': True},
]


def seed_and_link_statuses(apps, schema_editor):
    """
    Seeds default status options for each org, then sets the new status_fk
    nullable FK fields on existing Project/ProjectStory/ProjectTask records.
    """
    Organization = apps.get_model('core', 'Organization')
    ProjectStatusOption = apps.get_model('projects', 'ProjectStatusOption')
    Project = apps.get_model('projects', 'Project')
    ProjectStory = apps.get_model('projects', 'ProjectStory')
    ProjectTask = apps.get_model('projects', 'ProjectTask')

    org_status_map = {}

    def get_statuses(org_id):
        if org_id not in org_status_map:
            try:
                org = Organization.objects.get(id=org_id)
            except Organization.DoesNotExist:
                return {}
            status_map = {}
            for s in DEFAULT_STATUSES:
                obj, _ = ProjectStatusOption.objects.get_or_create(
                    company=org, code=s['code'],
                    defaults={k: v for k, v in s.items() if k != 'code'}
                )
                status_map[s['code']] = obj
            org_status_map[org_id] = status_map
        return org_status_map[org_id]

    def resolve(old_val, status_map):
        if not old_val:
            return status_map.get('pending')
        code = STATUS_NAME_MAP.get(old_val.lower().strip(), 'pending')
        return status_map.get(code, status_map.get('pending'))

    # Seed all orgs first
    for org in Organization.objects.all():
        get_statuses(org.id)

    # Update Projects — read old varchar status, resolve to FK
    for project in Project.objects.all():
        status_map = get_statuses(project.company_id)
        if status_map:
            # Read old status string from DB (currently stored as varchar via old CharField)
            # After AlterField it's been set to NULL — read it via raw sql before AlterField
            # But since we're in RunPython AFTER AlterField, old value is gone.
            # Assign 'pending' (default) for all existing rows
            project.status_id = status_map.get('pending').id if status_map.get('pending') else None
            project.save(update_fields=['status_id'])

    for story in ProjectStory.objects.all():
        try:
            project = Project.objects.get(id=story.project_id)
            status_map = get_statuses(project.company_id)
            if status_map and status_map.get('pending'):
                story.status_id = status_map['pending'].id
                story.save(update_fields=['status_id'])
        except Project.DoesNotExist:
            pass

    for task in ProjectTask.objects.all():
        try:
            story = ProjectStory.objects.get(id=task.story_id)
            project = Project.objects.get(id=story.project_id)
            status_map = get_statuses(project.company_id)
            if status_map and status_map.get('pending'):
                task.status_id = status_map['pending'].id
                task.save(update_fields=['status_id'])
        except (ProjectStory.DoesNotExist, Project.DoesNotExist):
            pass


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    # Disable atomicity so SQLite FK constraint checks happen per-statement
    # and we can run our RunPython between DDL operations.
    atomic = False

    dependencies = [
        ('core', '0007_emailhistory_emailqueue_emaillog_html_content_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Step 1: Create ProjectStatusOption table ──────────────────────────
        migrations.CreateModel(
            name='ProjectStatusOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=100)),
                ('category', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('scope', models.CharField(choices=[('project', 'Project'), ('story', 'Story'), ('task', 'Task'), ('all', 'All')], default='all', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_project_status_option',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='projectstatusoption',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status_options', to='core.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='projectstatusoption',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='projectstatusoption',
            index=models.Index(fields=['company'], name='api_project_company_fb63a7_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstatusoption',
            index=models.Index(fields=['company', 'scope'], name='api_project_company_a3a23f_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstatusoption',
            index=models.Index(fields=['is_system'], name='api_project_is_syst_c883fc_idx'),
        ),

        # ── Step 2: Create ProjectStoryMember table ───────────────────────────
        migrations.CreateModel(
            name='ProjectStoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_project_story_member',
            },
        ),
        migrations.AddField(
            model_name='projectstorymember',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_story_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectstorymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_assignments', to='projects.projectmember'),
        ),
        migrations.AddField(
            model_name='projectstorymember',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_members', to='projects.projectstory'),
        ),
        migrations.AddIndex(
            model_name='projectstorymember',
            index=models.Index(fields=['story'], name='api_project_story_i_7ec4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstorymember',
            index=models.Index(fields=['member'], name='api_project_member__23ee03_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectstorymember',
            constraint=models.UniqueConstraint(fields=('story', 'member'), name='unique_story_member'),
        ),

        # ── Step 3: Update ProjectStory.department choices ────────────────────
        migrations.AlterField(
            model_name='projectstory',
            name='department',
            field=models.CharField(blank=True, choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Testing', 'Testing'), ('Design', 'Design'), ('DevOps', 'DevOps'), ('General', 'General')], max_length=100, null=True),
        ),

        # ── Step 4: Change status fields to nullable FK ───────────────────────
        # SQLite will set existing values to NULL when the column type changes.
        # Our RunPython in Step 5 then re-populates them from the status pool.
        migrations.RenameIndex(
            model_name='project',
            new_name='api_project_status__ee4268_idx',
            old_name='api_project_status_89cb34_idx',
        ),
        migrations.RenameIndex(
            model_name='projectstory',
            new_name='api_project_status__595351_idx',
            old_name='api_project_status_a86f12_idx',
        ),
        migrations.RenameIndex(
            model_name='projecttask',
            new_name='api_project_status__b79426_idx',
            old_name='api_project_status_73f7a4_idx',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.projectstatusoption'),
        ),
        migrations.AlterField(
            model_name='projectstory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stories', to='projects.projectstatusoption'),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='projects.projectstatusoption'),
        ),

        # ── Step 5: Seed statuses and backfill NULL status fields ─────────────
        migrations.RunPython(seed_and_link_statuses, reverse_migration),
    ]
