# Generated by Django 5.2.1 on 2026-07-27 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailhistory_emailqueue_emaillog_html_content_and_more'),
        ('projects', '0003_seed_default_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.PositiveIntegerField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_project_activity',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_attachments/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_project_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_project_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectEpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('key', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#3b82f6', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'api_project_epic',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('goal', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'api_project_sprint',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSprintEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sprint_started', 'Sprint Started'), ('story_added', 'Story Added'), ('story_removed', 'Story Removed'), ('points_changed', 'Points Changed'), ('story_completed', 'Story Completed'), ('sprint_completed', 'Sprint Completed'), ('daily_snapshot', 'Daily Snapshot')], max_length=30)),
                ('points_delta', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('completed_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'api_project_sprint_event',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('estimated_hours', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'api_project_subtask',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='projectstory',
            name='api_project_departm_4a1732_idx',
        ),
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='acceptance_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='story_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='story_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='estimated_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='logged_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='task_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='projectstatusoption',
            name='scope',
            field=models.CharField(choices=[('project', 'Project'), ('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('all', 'All')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectstory',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.projectstory'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectstory'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectepic',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='core.organization'),
        ),
        migrations.AddField(
            model_name='projectepic',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_epics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectepic',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epics', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectepic',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='epics', to='projects.projectstatusoption'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectepic'),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='projects.projectepic'),
        ),
        migrations.AddField(
            model_name='projectsprint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsprint',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='projects.projectsprint'),
        ),
        migrations.AddIndex(
            model_name='projectstory',
            index=models.Index(fields=['sprint'], name='api_project_sprint__b077b2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstory',
            index=models.Index(fields=['epic'], name='api_project_epic_id_e470c5_idx'),
        ),
        migrations.AddField(
            model_name='projectsprintevent',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.projectsprint'),
        ),
        migrations.AddField(
            model_name='projectsprintevent',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprint_events', to='projects.projectstory'),
        ),
        migrations.AddField(
            model_name='projectsubtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsubtask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subtasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsubtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='projects.projecttask'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.projectsubtask'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project'], name='api_project_project_5a9557_idx'),
        ),
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['created_at'], name='api_project_created_eeaf06_idx'),
        ),
        migrations.AddIndex(
            model_name='projectepic',
            index=models.Index(fields=['project'], name='api_project_project_cd512e_idx'),
        ),
        migrations.AddIndex(
            model_name='projectepic',
            index=models.Index(fields=['company'], name='api_project_company_636ee2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectepic',
            index=models.Index(fields=['status'], name='api_project_status__e455be_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsprint',
            index=models.Index(fields=['project'], name='api_project_project_28dd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsprint',
            index=models.Index(fields=['status'], name='api_project_status_59750c_idx'),
        ),
        migrations.AddConstraint(
            model_name='projectsprint',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('project',), name='unique_active_sprint_per_project'),
        ),
        migrations.AddIndex(
            model_name='projectsprintevent',
            index=models.Index(fields=['sprint'], name='api_project_sprint__430726_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsprintevent',
            index=models.Index(fields=['created_at'], name='api_project_created_1ba332_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubtask',
            index=models.Index(fields=['task'], name='api_project_task_id_315cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsubtask',
            index=models.Index(fields=['is_completed'], name='api_project_is_comp_07db92_idx'),
        ),
    ]
