# Generated by Django 5.2.1 on 2026-07-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectactivity_projectattachment_projectcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('Client', 'Client'), ('Maintenance', 'Maintenance'), ('Research', 'Research')], default='Internal', max_length=50),
        ),
    ]
