# Generated by Django 5.2.1 on 2026-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstory',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectstory',
            name='work_type',
            field=models.CharField(default='Feature', max_length=50),
        ),
    ]
