# Generated by Django 5.2.1 on 2026-08-01 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectsprint_cancellation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed')], default='open', max_length=20)),
                ('happiness_score', models.FloatField(default=3.5)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retrospectives', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='projects.project')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrospectives', to='projects.projectsprint')),
            ],
            options={
                'db_table': 'api_project_retrospective',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRetrospectiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('went_well', 'What Went Well'), ('didnt_go_well', "What Didn't Go Well"), ('action_item', 'Action Item'), ('lesson_learned', 'Lesson Learned')], max_length=30)),
                ('text', models.TextField()),
                ('votes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrospective_action_items', to='projects.projectstory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retro_items', to=settings.AUTH_USER_MODEL)),
                ('retrospective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.projectretrospective')),
            ],
            options={
                'db_table': 'api_project_retrospective_item',
                'ordering': ['-votes', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVCSIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], default='github', max_length=20)),
                ('repository_name', models.CharField(max_length=255)),
                ('repository_url', models.URLField()),
                ('default_branch', models.CharField(default='main', max_length=100)),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_transition', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vcs_integrations', to='projects.project')),
            ],
            options={
                'db_table': 'api_project_vcs_integration',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVCSCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=150)),
                ('author_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vcs_commits', to='projects.projectstory')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vcs_commits', to='projects.projecttask')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='projects.projectvcsintegration')),
            ],
            options={
                'db_table': 'api_project_vcs_commit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVCSPullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('source_branch', models.CharField(max_length=100)),
                ('target_branch', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=150)),
                ('url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.projectvcsintegration')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vcs_pull_requests', to='projects.projectstory')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vcs_pull_requests', to='projects.projecttask')),
            ],
            options={
                'db_table': 'api_project_vcs_pull_request',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDailyStandup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('yesterday', models.TextField()),
                ('today', models.TextField()),
                ('blockers', models.TextField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(default=0.0)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='standup_attachments/%Y/%m/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_standups', to='projects.project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_standups', to='projects.projectsprint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_standups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_project_daily_standup',
                'ordering': ['-date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'date'), name='unique_daily_standup_per_user_date')],
            },
        ),
    ]
