# Generated by Django 5.2.15 on 2026-08-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectretrospectiveitem_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.projectepic'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='is_inline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project'),
        ),
    ]
