# Generated by Django 5.2.1 on 2026-08-04 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailhistory_emailqueue_emaillog_html_content_and_more'),
        ('projects', '0010_projectattachment_epic_projectattachment_is_inline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_attachments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='draft_token',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectattachment',
            name='is_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='projectattachment',
            index=models.Index(fields=['draft_token'], name='api_project_draft_t_b3d5ac_idx'),
        ),
        migrations.AddIndex(
            model_name='projectattachment',
            index=models.Index(fields=['is_temporary', 'expires_at'], name='api_project_is_temp_3f80eb_idx'),
        ),
    ]
