# Generated by Django 5.2.15 on 2026-08-07 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectattachment_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.projectcomment'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='client_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
