# Generated by Django 5.2.15 on 2026-08-10 14:30

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_projectattachment_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectattachment',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PureWindowsPath('C:/Users/user/Documents/project/fadi/1/cubelogs/backend/private_media')), upload_to='project_attachments/%Y/%m/'),
        ),
    ]
