# Generated by Django 5.2.15 on 2026-08-11 07:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_projectattachment_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='projectactivity',
            index=models.Index(fields=['project', 'created_at'], name='activity_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['story', 'created_at'], name='comment_story_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['task', 'created_at'], name='comment_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstory',
            index=models.Index(fields=['project', 'status'], name='story_project_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projectstory',
            index=models.Index(fields=['project', 'sprint'], name='story_project_sprint_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['story', 'status'], name='task_story_status_idx'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['story', 'assigned_to'], name='task_story_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='projectvcscommit',
            index=models.Index(fields=['integration', 'commit_hash'], name='vcs_commit_int_hash_idx'),
        ),
    ]
