# Generated by Django 5.2.15 on 2026-08-12 05:23

import django.core.validators
from django.db import migrations, models


def populate_progress_percentages(apps, schema_editor):
    ProjectStatusOption = apps.get_model('projects', 'ProjectStatusOption')
    for status in ProjectStatusOption.objects.all():
        cat = (status.category or '').lower()
        code = (status.code or '').lower()
        if cat == 'pending':
            status.progress_percentage = 0
        elif cat == 'completed':
            status.progress_percentage = 100
        elif cat == 'active':
            if code == 'review':
                status.progress_percentage = 75
            elif code == 'testing':
                status.progress_percentage = 85
            else:
                status.progress_percentage = 50
        else:
            status.progress_percentage = 0
        status.save(update_fields=['progress_percentage'])


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_projectactivity_activity_project_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstatusoption',
            name='progress_percentage',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.RunPython(populate_progress_percentages, reverse_populate),
    ]
