# Generated by Django 5.2.15 on 2026-08-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_add_progress_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectDailyStandup',
        ),
        migrations.DeleteModel(
            name='ProjectVCSCommit',
        ),
        migrations.DeleteModel(
            name='ProjectVCSPullRequest',
        ),
        migrations.DeleteModel(
            name='ProjectVCSIntegration',
        ),
    ]
