# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_projecttask_task_assignee_status_idx'),
        ('users', '0012_backfill_employee_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='assigned_to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_tasks', to='users.employeeprofile'),
        ),
        migrations.AddIndex(
            model_name='projecttask',
            index=models.Index(fields=['assigned_to_profile', 'status'], name='task_prof_status_idx'),
        ),
    ]
