# Generated by Django 5.2.15 on 2026-09-08 06:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_orgsettings_billing_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_module', models.CharField(default='projects', help_text="Module originating the file (e.g. 'projects')", max_length=50)),
                ('source_model', models.CharField(default='ProjectAttachment', help_text='Django model name of the source record', max_length=50)),
                ('source_object_id', models.CharField(db_index=True, help_text='Primary key/UUID of the source record (stable, non-empty string)', max_length=128)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(help_text='Storage-relative file path or storage reference key', max_length=1024)),
                ('storage_backend', models.CharField(default='private_filesystem', help_text='Storage backend identifier', max_length=50)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when customer deleted the file (stops billable lifecycle)', null=True)),
                ('purged_at', models.DateTimeField(blank=True, help_text='Timestamp when physical file was purged from backend disk/storage', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted'), ('PURGED', 'Purged')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_storage_files', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Canonical tenant organization that owns this billable file', on_delete=django.db.models.deletion.PROTECT, related_name='storage_files', to='core.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_storage_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storage_billing_file',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('UPLOAD', 'Upload'), ('DELETE', 'Delete'), ('PURGE', 'Purge')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('size_bytes', models.BigIntegerField(help_text='Snapshot of file size at event time')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Canonical tenant organization for event isolation', on_delete=django.db.models.deletion.PROTECT, related_name='storage_events', to='core.organization')),
                ('storage_file', models.ForeignKey(help_text='Target StorageFile record', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='storage_billing.storagefile')),
            ],
            options={
                'db_table': 'storage_billing_event',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageDailyUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('usage_date', models.DateField(db_index=True, help_text='UTC calendar date of usage')),
                ('billable_bytes', models.BigIntegerField(default=0, help_text='Sum of size_bytes for all distinct files present at any point during usage_date')),
                ('billable_gb', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Exact commercial decimal GB: billable_bytes / 1,000,000,000', max_digits=20)),
                ('storage_credits', models.PositiveIntegerField(default=0, help_text='Whole storage credits (ceil of billable_bytes / credit_size_bytes, or 0 if 0 bytes)')),
                ('storage_credit_size_bytes_snapshot', models.BigIntegerField(default=1000000000, help_text='Snapshot of storage_credit_size_bytes used for calculation')),
                ('monthly_credit_price_snapshot', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Price per credit per month at calculation time', max_digits=20)),
                ('daily_credit_rate_snapshot', models.DecimalField(decimal_places=12, default=Decimal('0E-12'), help_text='monthly_credit_price / days_in_month (high precision Decimal, 12 places)', max_digits=30)),
                ('storage_charge', models.DecimalField(decimal_places=12, default=Decimal('0E-12'), help_text='Daily storage charge unrounded to currency cents: credits * monthly_credit_price / days_in_month (12 places)', max_digits=30)),
                ('days_in_month', models.PositiveSmallIntegerField(default=30, help_text='Calendar days in that usage month (28, 29, 30, or 31)')),
                ('calculation_version', models.PositiveSmallIntegerField(default=1, help_text='Version of the calculation formula applied')),
                ('is_finalized', models.BooleanField(default=False, help_text='True if the usage day has passed and charge is permanently frozen')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='Organization for this daily usage snapshot', on_delete=django.db.models.deletion.PROTECT, related_name='storage_daily_usages', to='core.organization')),
            ],
            options={
                'db_table': 'storage_billing_daily_usage',
                'ordering': ['-usage_date', 'organization'],
                'indexes': [models.Index(fields=['organization', 'usage_date'], name='storage_usage_org_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'usage_date'), name='unique_org_usage_date')],
            },
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['organization', 'status', 'uploaded_at'], name='storage_file_org_stat_up_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['organization', 'deleted_at'], name='storage_file_org_del_idx'),
        ),
        migrations.AddIndex(
            model_name='storagefile',
            index=models.Index(fields=['source_module', 'source_object_id'], name='storage_file_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='storagefile',
            constraint=models.UniqueConstraint(fields=('organization', 'source_module', 'source_model', 'source_object_id'), name='unique_storage_file_source_per_org'),
        ),
        migrations.AddIndex(
            model_name='storageevent',
            index=models.Index(fields=['organization', 'event_type', 'occurred_at'], name='storage_event_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='storageevent',
            index=models.Index(fields=['storage_file', 'occurred_at'], name='storage_event_file_occ_idx'),
        ),
    ]
