# Generated by Django 5.2.15 on 2026-07-10 23:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ipAddress', models.CharField(blank=True, max_length=45, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'api_auditlog',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'api_organization',
            },
        ),
        migrations.CreateModel(
            name='OrganizationModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('module_id', models.CharField(max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_organizationmodule',
            },
        ),
        migrations.CreateModel(
            name='OrgSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('brandLogo', models.TextField(blank=True, null=True)),
                ('subscriptionDays', models.IntegerField(default=12)),
                ('subscriptionRenewedAt', models.DateTimeField(auto_now_add=True)),
                ('max_employees_allowed', models.IntegerField(default=10)),
                ('subscriptionStatus', models.CharField(default='Active', max_length=50)),
                ('subscriptionExpiresAt', models.DateTimeField(blank=True, null=True)),
                ('has_sent_billing_warning', models.BooleanField(default=False)),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('half_day_threshold_minutes', models.IntegerField(default=240)),
                ('full_day_absent_threshold_minutes', models.IntegerField(default=60)),
                ('auto_approve_attendance', models.BooleanField(default=False)),
                ('default_weekly_holidays', models.JSONField(blank=True, default=core.models.default_weekly_holidays_default)),
                ('monthly_recurring_holidays', models.JSONField(blank=True, default=list)),
                ('yearly_recurring_holidays', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'api_orgsettings',
            },
        ),
    ]
