# Generated by Django 5.2.15 on 2026-07-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
