# Generated by Django 5.2.15 on 2026-07-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orgsettings_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(default=False)),
                ('maintenance', models.BooleanField(default=False)),
                ('down', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mode',
                'verbose_name_plural': 'modes',
                'db_table': 'api_mode',
            },
        ),
    ]
