# Generated by Django 5.2.1 on 2026-07-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
            ],
            options={
                'verbose_name': 'Email Delivery History',
                'verbose_name_plural': 'Email Delivery History',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.emaillog',),
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
            ],
            options={
                'verbose_name': 'Email Queue (Pending)',
                'verbose_name_plural': 'Email Queue (Pending)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.emaillog',),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='html_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='template_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
