# Generated by Django 5.2.1 on 2026-08-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailhistory_emailqueue_emaillog_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='payroll_currency',
            field=models.CharField(default='USD', max_length=10),
        ),
    ]
