# Generated by Django 5.2.1 on 2026-08-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_orgsettings_payroll_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='payroll_proration_basis',
            field=models.CharField(choices=[('WORKING_DAYS', 'Working Days'), ('CALENDAR_DAYS', 'Calendar Days'), ('FIXED_30', 'Fixed 30 Days')], default='WORKING_DAYS', max_length=20),
        ),
    ]
