# Generated by Django 5.2.1 on 2026-08-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orgsettings_payroll_proration_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='company_address',
            field=models.TextField(blank=True, help_text='Official business address', null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='company_tax_id',
            field=models.CharField(blank=True, help_text='Tax / VAT / TRN / Registration Number', max_length=50, null=True),
        ),
    ]
