# Generated by Django 5.2.15 on 2026-08-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orgsettings_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='daily_wage_paid_leave_eligible',
            field=models.BooleanField(default=True, help_text='When True, approved paid leaves contribute to daily wage payable days.'),
        ),
        migrations.AlterField(
            model_name='orgsettings',
            name='payroll_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
