# Generated by Django 5.2.15 on 2026-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_orgsettings_daily_wage_paid_leave_eligible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='hourly_wage_paid_leave_eligible',
            field=models.BooleanField(default=True, help_text='When True, approved paid leaves contribute scheduled payable hours for hourly wage employees.'),
        ),
    ]
