# Generated by Django 5.2.15 on 2026-08-28 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_orgsettings_hourly_wage_paid_leave_eligible'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', '-createdAt'], name='auditlog_org_created_idx'),
        ),
    ]
