# Generated by Django 5.2.15 on 2026-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auditlog_auditlog_org_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='payroll_frequency',
            field=models.CharField(choices=[('MONTHLY', 'Monthly')], default='MONTHLY', help_text='Organization payroll processing frequency', max_length=20),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='payroll_processing_day',
            field=models.IntegerField(default=28, help_text='Planned day of month for processing monthly payroll (1-31)'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='salary_payment_day',
            field=models.IntegerField(default=1, help_text='Planned day of month for disbursing monthly salaries (1-31)'),
        ),
    ]
