# Generated by Django 5.2.1 on 2026-09-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_orgsettings_payroll_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Optional organization billing contact email for invoices and notifications', max_length=254, null=True),
        ),
    ]
