# Generated by Django 5.2.15 on 2026-09-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orgsettings_billing_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='corporate_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='corporate_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='corporate_bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='corporate_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='corporate_client_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='corporate_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
