# Generated by Django 5.2.1 on 2026-06-18 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='api.organization'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(default='Success', max_length=50),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
