# Generated by Django 5.2.1 on 2026-06-18 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wallet_organization_wallet_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='receiptUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
