# Generated by Django 5.2.1 on 2026-06-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_wallettransaction_receipturl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='receiptUrl',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
