# Generated by Django 5.2.1 on 2026-06-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_wallettransaction_receipturl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='is_attendance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='is_project_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='max_employees_allowed',
            field=models.IntegerField(default=10),
        ),
    ]
