# Generated by Django 5.2.15 on 2026-06-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_orgsettings_is_attendance_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='subscriptionStatus',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
