# Generated by Django 5.2.15 on 2026-06-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_orgsettings_subscriptionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='subscriptionExpiresAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
