# Generated by Django 5.2.15 on 2026-06-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_orgsettings_subscriptionexpiresat'),
    ]

    operations = [
        migrations.AddField(
            model_name='officelocation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.organization'),
        ),
    ]
