# Generated by Django 5.2.1 on 2026-06-19 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_officelocation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='minAdvanceDays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='api.organization'),
        ),
    ]
