# Generated by Django 5.2.1 on 2026-06-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_leavetype_minadvancedays_leavetype_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='has_sent_billing_warning',
            field=models.BooleanField(default=False),
        ),
    ]
