# Generated by Django 5.2.1 on 2026-06-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_subscriptionpackage_price_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Pending Approval', max_length=50),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='full_day_absent_threshold_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='grace_period_minutes',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='half_day_threshold_minutes',
            field=models.IntegerField(default=240),
        ),
    ]
