# Generated by Django 5.2.15 on 2026-06-26 21:17

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_attendancelog_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='api.organization'),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='default_weekly_holidays',
            field=models.JSONField(blank=True, default=api.models.default_weekly_holidays_default),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='monthly_recurring_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orgsettings',
            name='yearly_recurring_holidays',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
