# Generated by Django 5.2.1 on 2026-06-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_holiday_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgsettings',
            name='auto_approve_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
