# Generated by Django 5.2.15 on 2026-06-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_lead_assigned_staff_lead_created_at_lead_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
