# Generated by Django 5.2.15 on 2026-06-29 01:41

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_wallettransaction_invoice_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=api.models.default_coupon_code, max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage')], default='Percentage', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_deposit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
