# Generated by Django 5.2.1 on 2026-07-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_emailqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='blackout_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='blackout_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='html_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='scheduled_send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
