# Generated by Django 5.2.1 on 2026-07-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_emailqueue_blackout_end_emailqueue_blackout_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailqueue',
            name='blackout_end',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='blackout_start',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='html_body',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='scheduled_send_time',
        ),
    ]
