# Generated by Django 5.2.1 on 2026-07-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_emailqueue_blackout_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='html_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
