# Generated by Django 5.2.1 on 2026-07-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='template_type',
            field=models.CharField(choices=[('WELCOME', 'User Registration Welcome Email'), ('LOW_BALANCE', 'Low Wallet Alert'), ('DEBIT_INVOICE', 'Standard Transaction Invoice'), ('SUBSCRIPTION_EXPIRED', 'Subscription Expired Notice'), ('DATA_KEEPING_FEE', 'Monthly Data Maintenance Invoice')], max_length=20),
        ),
    ]
