# Generated by Django 5.2.1 on 2026-07-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_emaillog_template_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
