# Generated by Django 5.2.15 on 2026-07-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_promovideosection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='video_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
