# Generated by Django 5.2.15 on 2026-07-03 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_subscriptionpackage_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('author_initials', models.CharField(blank=True, max_length=10, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_title', models.CharField(max_length=255)),
                ('bg_color', models.CharField(default='var(--primary)', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
