# Generated by Django 5.2.15 on 2026-07-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
