# Generated by Django 5.2.15 on 2026-07-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_emaillog_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
