# Generated by Django 5.2.15 on 2026-07-05 21:28

from django.db import migrations

def remove_staff_superuser_from_customers(apps, schema_editor):
    Employee = apps.get_model('api', 'Employee')
    # Update all Employee records that belong to an organization
    # to set is_staff=False and is_superuser=False.
    Employee.objects.filter(organization__isnull=False).update(is_staff=False, is_superuser=False)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_employee_raw_password'),
    ]

    operations = [
        migrations.RunPython(remove_staff_superuser_from_customers),
    ]
