# Generated by Django 5.2.1 on 2026-08-20 05:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendanceperiodemployeesnapshot_paid_leave_days_and_more'),
        ('core', '0009_orgsettings_payroll_proration_basis'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponent',
            name='is_proratable',
            field=models.BooleanField(default=True, help_text='Subject to attendance / unpaid leave proration'),
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Calculated', 'Calculated'), ('Finalized', 'Finalized')], db_index=True, default='Draft', max_length=20)),
                ('current_revision', models.PositiveIntegerField(default=0)),
                ('attendance_revision', models.PositiveIntegerField(default=0, help_text='Attendance snapshot revision consumed.')),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('proration_basis', models.CharField(default='WORKING_DAYS', max_length=20)),
                ('total_employees', models.IntegerField(default=0)),
                ('total_base_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_attendance_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_earned_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_base_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_adjustments_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_periods', to='attendance.attendanceperiod')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payrolls', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_payrolls', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='core.organization')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_payrollperiod',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollEmployeeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('salary_effective_from', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('working_days', models.IntegerField(default=0)),
                ('payable_attendance_units', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('absent_days', models.IntegerField(default=0)),
                ('base_gross_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('base_fixed_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('base_net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('proratable_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('non_proratable_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('daily_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('attendance_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('earned_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('additional_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('additional_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('salary_components_snapshot', models.JSONField(default=list)),
                ('attendance_summary_snapshot', models.JSONField(default=dict)),
                ('calculation_breakdown', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('NegativeNet', 'Negative Net Pay'), ('MissingSalaryStructure', 'Missing Salary Structure'), ('NotEligible', 'Not Eligible'), ('NeedsReview', 'Needs Review')], default='OK', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_snapshots', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_snapshots', to='payroll.employeesalarystructure')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_snapshots', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'api_payrollemployeesnapshot',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('adjustment_type', models.CharField(choices=[('Earning', 'Earning'), ('Deduction', 'Deduction')], max_length=20)),
                ('category', models.CharField(choices=[('Bonus', 'Bonus'), ('Commission', 'Commission'), ('Reimbursement', 'Reimbursement'), ('Fine', 'Fine / Penalty'), ('AdvanceRecovery', 'Salary Advance Recovery'), ('Other', 'Other Adjustment')], default='Bonus', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to='core.organization')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'api_payrolladjustment',
                'ordering': ['employee', 'adjustment_type', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'month'), name='unique_org_year_month_payroll_period'),
        ),
        migrations.AddConstraint(
            model_name='payrollemployeesnapshot',
            constraint=models.UniqueConstraint(fields=('payroll_period', 'employee', 'revision'), name='unique_payroll_period_employee_revision'),
        ),
    ]
