# Generated by Django 5.2.1 on 2026-08-20 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_orgsettings_company_address_and_more'),
        ('payroll', '0002_salarycomponent_is_proratable_payrollperiod_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('payslip_number', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Superseded', 'Superseded')], db_index=True, default='Issued', max_length=20)),
                ('company_name_snapshot', models.CharField(max_length=255)),
                ('company_details_snapshot', models.JSONField(default=dict)),
                ('employee_details_snapshot', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payslips', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='core.organization')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='payroll.payrollperiod')),
                ('payroll_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_payslips', to='payroll.payrollemployeesnapshot')),
            ],
            options={
                'db_table': 'api_payslip',
                'ordering': ['-payroll_period__year', '-payroll_period__month', 'employee'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'payroll_period', 'employee', 'revision'), name='unique_org_period_employee_revision_payslip'), models.UniqueConstraint(fields=('organization', 'payslip_number'), name='unique_org_payslip_number')],
            },
        ),
    ]
