# Generated by Django 5.2.15 on 2026-08-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarystructure',
            name='compensation_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Salary'), ('DAILY', 'Daily Wage')], db_index=True, default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='employeesalarystructure',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contractual rate per payable day (for DAILY compensation type)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployeesnapshot',
            name='compensation_type',
            field=models.CharField(default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeesalarystructure',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='payrollemployeesnapshot',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
