# Generated by Django 5.2.15 on 2026-08-21 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeesalarystructure_compensation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarystructure',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contractual rate per payable work hour (for HOURLY compensation type)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployeesnapshot',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Contractual hourly rate for HOURLY compensation type', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployeesnapshot',
            name='payable_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Finalized payable work hours for HOURLY calculation', max_digits=8),
        ),
        migrations.AlterField(
            model_name='employeesalarystructure',
            name='compensation_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly Salary'), ('DAILY', 'Daily Wage'), ('HOURLY', 'Hourly Wage')], db_index=True, default='MONTHLY', max_length=20),
        ),
    ]
