# Generated by Django 5.2.15 on 2026-08-28 07:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auditlog_auditlog_org_created_idx'),
        ('payroll', '0005_employeesalarystructure_hourly_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('BankTransfer', 'Bank Transfer'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Other', 'Other')], default='BankTransfer', max_length=30)),
                ('transaction_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Voided', 'Voided')], db_index=True, default='Paid', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='core.organization')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='payroll.payrollperiod')),
                ('payroll_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='payroll.payrollemployeesnapshot')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_salarypayment',
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'payroll_period', 'status'], name='api_salaryp_organiz_3a0f91_idx'), models.Index(fields=['employee', 'paid_at'], name='api_salaryp_employe_8fff3a_idx'), models.Index(fields=['payroll_snapshot', 'status'], name='api_salaryp_payroll_1cc887_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'Paid')), fields=('payroll_snapshot',), name='unique_active_paid_salary_payment')],
            },
        ),
    ]
