# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_salarypayment'),
        ('users', '0012_backfill_employee_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarystructure',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='users.employeeprofile'),
        ),
    ]
