# Generated by Django 5.2.15 on 2026-07-12 22:21

import company.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('code', models.CharField(default=company.models.default_coupon_code, max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage')], default='Percentage', max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_deposit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_backofficecoupon',
            },
        ),
        migrations.CreateModel(
            name='CMSContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_cmscontent',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('discountType', models.CharField(default='Percentage', max_length=50)),
                ('discountValue', models.IntegerField(default=10)),
                ('usageLimit', models.IntegerField(default=100)),
                ('usageCount', models.IntegerField(default=0)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_coupon',
            },
        ),
        migrations.CreateModel(
            name='LMSModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='Coaching', max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_lmsmodule',
            },
        ),
        migrations.CreateModel(
            name='PromoVideoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('youtube_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_promovideosection',
            },
        ),
        migrations.CreateModel(
            name='SubscriberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('packageName', models.CharField(default='Free Package', max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_subscriberaccount',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('employeeLimit', models.IntegerField(default=10)),
                ('features', models.JSONField(blank=True, default=list)),
                ('isActive', models.BooleanField(default=True)),
                ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'api_subscriptionpackage',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('stars', models.IntegerField(default=5)),
                ('text', models.TextField()),
                ('author_initials', models.CharField(blank=True, max_length=10, null=True)),
                ('author_name', models.CharField(max_length=255)),
                ('author_title', models.CharField(max_length=255)),
                ('bg_color', models.CharField(default='var(--primary)', max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_testimonial',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('companyName', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_lead',
            },
        ),
        migrations.CreateModel(
            name='LeadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='company.lead')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_leadhistory',
            },
        ),
        migrations.CreateModel(
            name='MonthlyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('billing_month', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_email_sent', models.BooleanField(default=False)),
                ('deduction_reminder_sent', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='core.organization')),
            ],
            options={
                'db_table': 'api_monthlyinvoice',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='core.organization')),
            ],
            options={
                'db_table': 'api_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('transactionType', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('success', models.BooleanField(default=True)),
                ('stripeEventId', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('invoice_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='company.wallet')),
            ],
            options={
                'db_table': 'api_wallettransaction',
            },
        ),
    ]
