# Generated by Django 5.2.1 on 2026-07-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_backofficecoupon_created_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='SubscriberAccount',
                ),
                migrations.DeleteModel(
                    name='SubscriptionPackage',
                ),
            ],
            database_operations=[]
        )
    ]
