# Generated by Django 5.2.1 on 2026-07-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_delete_subscriberaccount_delete_subscriptionpackage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='BackofficeCoupon',
                ),
                migrations.DeleteModel(
                    name='Coupon',
                ),
                migrations.RemoveField(
                    model_name='wallet',
                    name='employee',
                ),
                migrations.RemoveField(
                    model_name='wallet',
                    name='organization',
                ),
                migrations.RemoveField(
                    model_name='wallettransaction',
                    name='wallet',
                ),
                migrations.DeleteModel(
                    name='MonthlyInvoice',
                ),
                migrations.DeleteModel(
                    name='Wallet',
                ),
                migrations.DeleteModel(
                    name='WalletTransaction',
                ),
            ],
            database_operations=[]
        ),
    ]
