# Generated by Django 5.2.15 on 2026-08-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_delete_backofficecoupon_delete_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
