# Generated by Django 5.2.1 on 2026-07-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_delete_subscriberaccount_delete_subscriptionpackage'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='SubscriberAccount',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('email', models.EmailField(max_length=254, unique=True)),
                        ('packageName', models.CharField(default='Free Package', max_length=255)),
                        ('isActive', models.BooleanField(default=True)),
                        ('expiresAt', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'api_subscriberaccount',
                    },
                ),
                migrations.CreateModel(
                    name='SubscriptionPackage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('name', models.CharField(max_length=255, unique=True)),
                        ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                        ('employeeLimit', models.IntegerField(default=10)),
                        ('features', models.JSONField(blank=True, default=list)),
                        ('isActive', models.BooleanField(default=True)),
                        ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
                    ],
                    options={
                        'db_table': 'api_subscriptionpackage',
                    },
                ),
            ],
            database_operations=[]
        )
    ]
