# Generated by Django 5.2.1 on 2026-07-14 00:27

import django.db.models.deletion
import subscribers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_organization'),
        ('subscribers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BackofficeCoupon',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('code', models.CharField(default=subscribers.models.default_coupon_code, max_length=100, unique=True)),
                        ('value_type', models.CharField(choices=[('Fixed Amount', 'Fixed Amount'), ('Percentage', 'Percentage')], default='Percentage', max_length=50)),
                        ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('min_deposit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                        ('is_active', models.BooleanField(default=True)),
                        ('expiry_date', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'api_backofficecoupon',
                    },
                ),
                migrations.CreateModel(
                    name='Coupon',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('code', models.CharField(max_length=100, unique=True)),
                        ('discountType', models.CharField(default='Percentage', max_length=50)),
                        ('discountValue', models.IntegerField(default=10)),
                        ('usageLimit', models.IntegerField(default=100)),
                        ('usageCount', models.IntegerField(default=0)),
                        ('expiresAt', models.DateTimeField(blank=True, null=True)),
                    ],
                    options={
                        'db_table': 'api_coupon',
                    },
                ),
                migrations.CreateModel(
                    name='MonthlyInvoice',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('billing_month', models.DateField()),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                        ('is_paid', models.BooleanField(default=False)),
                        ('paid_at', models.DateTimeField(blank=True, null=True)),
                        ('invoice_email_sent', models.BooleanField(default=False)),
                        ('deduction_reminder_sent', models.BooleanField(default=False)),
                        ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_invoices', to='core.organization')),
                    ],
                    options={
                        'db_table': 'api_monthlyinvoice',
                    },
                ),
                migrations.CreateModel(
                    name='Wallet',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                        ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
                        ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallets', to='core.organization')),
                    ],
                    options={
                        'db_table': 'api_wallet',
                    },
                ),
                migrations.CreateModel(
                    name='WalletTransaction',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('is_deleted', models.BooleanField(default=False)),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                        ('transactionType', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                        ('success', models.BooleanField(default=True)),
                        ('stripeEventId', models.CharField(blank=True, max_length=255, null=True)),
                        ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                        ('status', models.CharField(default='Success', max_length=50)),
                        ('details', models.TextField(blank=True, null=True)),
                        ('receipt_url', models.URLField(blank=True, max_length=1024, null=True)),
                        ('invoice_url', models.URLField(blank=True, max_length=1024, null=True)),
                        ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscribers.wallet')),
                    ],
                    options={
                        'db_table': 'api_wallettransaction',
                    },
                ),
            ],
            database_operations=[]
        ),
    ]
