# Generated by Django 5.2.1 on 2026-07-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0002_backofficecoupon_coupon_monthlyinvoice_wallet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('monthly_subscription_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('monthly_data_rent', models.DecimalField(decimal_places=2, default=50.0, max_digits=20)),
                ('attendance_module_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('tasks_module_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('employee_seat_price', models.DecimalField(decimal_places=2, default=100.0, max_digits=20)),
                ('grace_period_days', models.IntegerField(default=5)),
                ('reminder_email_days_before', models.IntegerField(default=1)),
                ('auto_deduction_day', models.IntegerField(default=5)),
                ('invoice_generation_day', models.IntegerField(default=1)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'api_globalbillingsettings',
            },
        ),
    ]
