# Generated by Django 5.2.1 on 2026-09-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_orgsettings_billing_email'),
        ('subscribers', '0003_globalbillingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='attendance_enabled_snapshot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='attendance_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='base_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='employee_count_snapshot',
            field=models.IntegerField(blank=True, help_text='Billable employee count at invoice creation time', null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='employee_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='employee_unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Monthly Subscription'), ('DATA_RETENTION', 'Data Retention Rent')], default='SUBSCRIPTION', help_text='Category of invoice', max_length=50),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='project_enabled_snapshot',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='project_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='subtotal_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='tax_amount_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='tax_percentage_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddConstraint(
            model_name='monthlyinvoice',
            constraint=models.UniqueConstraint(fields=('organization', 'billing_month', 'invoice_type'), name='unique_org_billing_month_type'),
        ),
    ]
