# Generated by Django 5.2.1 on 2026-09-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0004_monthlyinvoice_attendance_enabled_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='payment_failed_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='reactivation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='restriction_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
