# Generated by Django 5.2.15 on 2026-09-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_wallet_razorpay_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='attendance_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='attendance_unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='project_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='project_unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='globalbillingsettings',
            name='attendance_module_price',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='globalbillingsettings',
            name='employee_seat_price',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='globalbillingsettings',
            name='monthly_subscription_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='globalbillingsettings',
            name='tasks_module_price',
            field=models.DecimalField(decimal_places=2, default=56.0, max_digits=20),
        ),
    ]
