# Generated by Django 5.2.15 on 2026-09-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_monthlyinvoice_attendance_total_snapshot_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('razorpay_payment_id__isnull', False), ('success', True)), fields=('razorpay_payment_id',), name='unique_successful_razorpay_payment'),
        ),
    ]
