# Generated by Django 5.2.15 on 2026-09-08 05:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_wallettransaction_unique_successful_razorpay_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalbillingsettings',
            name='storage_billing_enabled',
            field=models.BooleanField(default=False, help_text='Global master toggle for storage billing'),
        ),
        migrations.AddField(
            model_name='globalbillingsettings',
            name='storage_credit_monthly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Monthly price per storage credit in currency', max_digits=20),
        ),
        migrations.AddField(
            model_name='globalbillingsettings',
            name='storage_credit_size_bytes',
            field=models.BigIntegerField(default=1000000000, help_text='Commercial decimal GB (1,000,000,000 bytes)'),
        ),
    ]
