# Generated by Django 5.2.15 on 2026-09-09 08:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_globalbillingsettings_storage_billing_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoice',
            name='storage_billable_bytes_days_snapshot',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='storage_charge_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='storage_credit_days_snapshot',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='storage_finalized_days_snapshot',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyinvoice',
            name='storage_usage_month_snapshot',
            field=models.DateField(blank=True, null=True),
        ),
    ]
