# Generated by Django 5.2.15 on 2026-07-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('employeeName', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('clockIn', models.DateTimeField(blank=True, null=True)),
                ('clockOut', models.DateTimeField(blank=True, null=True)),
                ('totalDuration', models.CharField(blank=True, max_length=50, null=True)),
                ('verificationPhoto', models.TextField(blank=True, null=True)),
                ('verificationLocation', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('Pending Approval', 'Pending Approval'), ('Approved', 'Approved'), ('Late', 'Late'), ('Half Day', 'Half Day'), ('Absent', 'Absent')], default='Pending Approval', max_length=50)),
            ],
            options={
                'db_table': 'api_attendancelog',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_holiday',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('employeeName', models.CharField(max_length=255)),
                ('leaveTypeName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('duration', models.FloatField(default=1.0)),
                ('dayType', models.CharField(default='Full', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
            options={
                'db_table': 'api_leave',
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('limitPeriod', models.CharField(default='Yearly', max_length=50)),
                ('maxLimit', models.IntegerField(default=10)),
                ('restrictedDates', models.JSONField(blank=True, default=list)),
                ('carryForward', models.BooleanField(default=False)),
                ('maxCarryForward', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('minAdvanceDays', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'api_leavetype',
            },
        ),
        migrations.CreateModel(
            name='OfficeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius', models.FloatField(default=100.0)),
                ('isPrimary', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_officelocation',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('designation', models.CharField(max_length=100, unique=True)),
                ('shiftStart', models.CharField(default='09:00', max_length=5)),
                ('shiftEnd', models.CharField(default='17:00', max_length=5)),
            ],
            options={
                'db_table': 'api_schedule',
            },
        ),
    ]
