# Generated by Django 5.2.15 on 2026-08-19 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_enforce_schedule_tenant_constraints'),
        ('core', '0007_emailhistory_emailqueue_emaillog_html_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Finalized', 'Finalized')], db_index=True, default='Draft', max_length=20)),
                ('current_revision', models.PositiveIntegerField(default=0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('total_employees', models.IntegerField(default=0)),
                ('payroll_ready_count', models.IntegerField(default=0)),
                ('needs_review_count', models.IntegerField(default=0)),
                ('reopen_reason', models.TextField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_attendance_periods', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_periods', to='core.organization')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_attendance_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_attendanceperiod',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePeriodEmployeeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(blank=True, default='', max_length=100)),
                ('working_days', models.IntegerField(default=0)),
                ('present_days', models.FloatField(default=0.0)),
                ('half_days', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('leave_days', models.FloatField(default=0.0)),
                ('payable_attendance_units', models.FloatField(default=0.0)),
                ('late_count', models.IntegerField(default=0)),
                ('total_late_minutes', models.IntegerField(default=0)),
                ('total_worked_minutes', models.IntegerField(default=0)),
                ('weekly_off_days', models.IntegerField(default=0)),
                ('holiday_days', models.IntegerField(default=0)),
                ('worked_on_off_days', models.IntegerField(default=0)),
                ('daily_summaries', models.JSONField(default=list)),
                ('attendance_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_snapshots', to='attendance.attendanceperiod')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_attendanceperiodemployeesnapshot',
                'ordering': ['employee_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendanceperiod',
            constraint=models.UniqueConstraint(fields=('organization', 'year', 'month'), name='unique_org_year_month_attendance_period'),
        ),
        migrations.AddConstraint(
            model_name='attendanceperiodemployeesnapshot',
            constraint=models.UniqueConstraint(fields=('attendance_period', 'employee', 'revision'), name='unique_period_emp_revision_snapshot'),
        ),
    ]
