# Generated by Django 5.2.1 on 2026-08-19 11:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendanceperiod_attendanceperiodemployeesnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceperiodemployeesnapshot',
            name='paid_leave_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='attendanceperiodemployeesnapshot',
            name='unpaid_leave_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
