# Generated by Django 5.2.15 on 2026-08-21 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendanceperiodemployeesnapshot_paid_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceperiodemployeesnapshot',
            name='payable_work_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Finalized payable work hours for hourly compensation calculation', max_digits=8),
        ),
    ]
