# Generated by Django 5.2.15 on 2026-08-28 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_attendancepolicy_minimum_session_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'date', 'is_deleted'], name='att_log_emp_date_del_idx'),
        ),
        migrations.AddIndex(
            model_name='leave',
            index=models.Index(fields=['employee', 'startDate', 'endDate', 'is_deleted'], name='leave_emp_dates_del_idx'),
        ),
    ]
