# Generated by Django 5.2.15 on 2026-09-14 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendancelog_att_log_emp_date_del_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'clockIn'], name='attlog_emp_clockin_idx'),
        ),
    ]
