# Generated by Django 5.2.15 on 2026-09-14 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_attendancelog_attlog_emp_clockin_idx'),
        ('users', '0012_backfill_employee_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='employee_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='users.employeeprofile'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee_profile', 'date'], name='attlog_prof_date_idx'),
        ),
    ]
